name: Daily get_yc_data Script Execution

on:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'

jobs:
  run-scrapy-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        # Add other dependencies 
          pip install --upgrade os
          pip install --upgrade json
          pip install --upgrade datetime
          pip install --upgrade requests
          pip install --upgrade bs4 

    - name: Run get_yc_data.py script
      run: |
        python ./scripts/get_yc_data.py
