name: Daily get_yc_data Script Execution

on:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'

jobs:
  run-scrapy-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' 

    - name: Upload Data Directory
      uses: actions/upload-artifact@v3
      with:
        name: data
        path: ./scripts/data

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        # Add other dependencies 
        python3 -m pip install --upgrade requests
        python3 -m pip install --upgrade bs4 

    - name: Run get_yc_data.py script
      run: |
        python3 ./scripts/get_yc_data.py
